name: "kibot"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        kicad: 5
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: action_ERC_results
        path: Generated

  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        kicad: 5
        dir: Generated
        skip: run_erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: action_DRC_results
        path: Generated


  # ERC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:dev_k6

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run ERC
  #     run: |
  #       make erc

  #   - name: Retrieve results
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: ERC_Output
  #       path: Generated

  # DRC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:dev_k6
  #   needs: ERC

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Run DRC
  #     run: |
  #       make drc

  #   - name: Retrieve results
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: DRC_Output
  #       path: Generated

