name: "kicad"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kicad.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kicad.yml'

jobs:
  # ERC:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version:
  #         - "PCIexpress_x1_full"
  #         - "PCIexpress_x1_half"
  #         - "PCIexpress_x16_low"
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:dev_k6
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run ERC
  #       working-directory: ./PCIe/${{ matrix.version }}
  #       run: |
  #         make erc

  #     - name: Retrieve results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ERC_${{ matrix.version }}
  #         path: ./PCIe/${{ matrix.version }}/Generated

  # DRC:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version:
  #         - "PCIexpress_x1_full"
  #         - "PCIexpress_x1_half"
  #         - "PCIexpress_x16_low"
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:dev_k6
  #   needs: ERC
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: "recursive"

  #     - name: Run DRC
  #       working-directory: ./PCIe/${{ matrix.version }}
  #       run: |
  #         make drc

  #     - name: Retrieve results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: DRC_${{ matrix.version }}
  #         path: ./PCIe/${{ matrix.version }}/Generated

  Fabrication:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "PCIexpress_x1_full"
          - "PCIexpress_x1_half"
          - "PCIexpress_x4_half"
          - "PCIexpress_x8_low"
          - "PCIexpress_x16_low"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: PCIe/configs/JLCPCB.kibot.yaml
          dir: PCIe/Fabrication/${{ matrix.version }}
          # optional - schematic file
          schema: 'PCIe/${{ matrix.version }}/${{ matrix.version }}.kicad_sch'
          # optional - PCB design file
          board: 'PCIe/${{ matrix.version }}/${{ matrix.version }}.kicad_pcb'

      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Fabrication_${{ matrix.version }}
          path: |
            PCIe/Fabrication/${{ matrix.version }}
          if-no-files-found: warn
